jupyter nbconvert Dataset1-Regression_output_1.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_2.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_3.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_4.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_5.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_6.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_7.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_8.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_9.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_10.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_11.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_12.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_13.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_14.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_15.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_16.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_17.ipynb --to pdf
jupyter nbconvert Dataset1-Regression_output_18.ipynb --to pdf